"""empty message

Revision ID: 0659c00bd7cc
Revises: 70b8e0866e39
Create Date: 2024-08-02 21:03:49.136240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0659c00bd7cc'
down_revision = '70b8e0866e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='imagen ilustrativa de la categoria',
               existing_nullable=True)

    with op.batch_alter_table('plato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorito', sa.Boolean(), nullable=False))
        batch_op.alter_column('imagen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='imagen del plato',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plato', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               comment='imagen del plato',
               existing_nullable=True)
        batch_op.drop_column('favorito')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               comment='imagen ilustrativa de la categoria',
               existing_nullable=True)

    # ### end Alembic commands ###
