"""empty message

Revision ID: 77379c1a50b1
Revises: c19e1c17e693
Create Date: 2024-07-30 22:39:34.679390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77379c1a50b1'
down_revision = 'c19e1c17e693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorito', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plato', schema=None) as batch_op:
        batch_op.drop_column('favorito')

    # ### end Alembic commands ###
